version: "4.0"
services:
  app:
    image: plamer88/skywars:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:5000
    depends_on:
      postgres:
        condition: service_healthy
#      create_db:
#        condition: service_completed_successfully

#  create_db:
#    image: plamer88/skywars:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#    depends_on:
#      postgres:
#        condition: service_healthy
#    volumes:
#      - ./create_db.py:/skywars/create_db.py
#    command: python3 create_db.py

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres_data:/var/lig/postgresql/data



