name: skywars copy and deploy
on: [push]
jobs:
  copy_files_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: clone git repository
        uses: appleboy/ssh-action@master
        with:
          host: 62.173.139.34
          username: root
          password: ${{secrets.SKYWARS_SERVER_PASS}}
          script: |
            cd /home/
            mkdir skywars
            cd skywars
            git clone https://github.com/plamer777/coursework_5.git .
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            cp skywars.service /etc/systemd/system
            systemctl daemon-reload
            systemctl start skywars
            systemctl enable skywars
